Gulp related upgrades and amendments, Readme changes, Edition eg change
guardian/open-platform-site pull request #76
Opened 2022-10-05 15:03 UTC by Divs-B

## Describe your changes

What has changed?

- Older version of Gulp which is no longer supported is removed, 
- package.json is added to support new version of gulp and other modules to get installed locally
- gulpfile.js has modified to support new gulp and ES module(latest ECMAscript version)
- Readme.md is updated
- Example on edition page is modified to have 'developer' key

Why is the change required?

- If we follow the instructions of existing Readme file (when working on repo locally) it does not produce the desired results and hence does not run on localhost. We need to upgrade to latest version of gulp and need to do related changes.
- 
## How to test

By following instructions in updated Readme

## How can we measure success?

By able to successfully running on localhost

## Have we considered potential risks?

2022-10-06 09:39 UTC, paulmr requested changes
Great work Divya, it is quite difficult to make a change like this to an old and neglected repository so I am really glad to see this getting done!

I have made a few comments in line.

A few other items:

+ After you moved the dependencies in `package.json` to `devDependencies` that has some implications for the `package-lock.json` so you should re-check that in after you run `npm install` in the repo.
+ I think it might be simpler to move the actual documentation changes into a separate PR as conceptually, the changes to the build system and the changes to the documentation are two different things.

<img width="251" alt="image" src="https://user-images.githubusercontent.com/2242307/194279548-2494f423-b164-421d-960e-5cec87a9b0f1.png">

Love these stats 😄  ☝️

2022-10-06 09:39 UTC, paulmr commented on README.md
>  gulp
I think we still need the `cd build` here, and then in order to avoid having to install `gulp` globally, we can just run something like `npx gulp` instead, as that will look in the locally installed module to find the executable.

2022-10-06 09:39 UTC, paulmr commented on build/gulpfile.js
> +    //.pipe(gulp.dest(out.css))
If we comment out these lines then we end up with a 'css' task that doesn't do anything. This is slightly confusing, but more importantly it stops the CSS from being generated, which means we can no longer make changes to the CSS. 

E.g, if I modify the `assets/css/common.css` file to change the font, this won't get reflected in the generated site because those files are no longer being copied into `public/` due to the removal of `.pipe(gulp.dest(out.css))`.

So we need to bring these lines back in again.

2022-10-06 09:39 UTC, paulmr commented on build/gulpfile.js
> +    //.pipe(minifyCSS(opts))
I think we should still be minifying the CSS. I assume the reason this was commented out was because the reference to `opts` triggers an error with the latest version of gulp, probably because something changed that means the gulp file is now running in "strict mode" or similar. Anyway, this can be easily resolved by just removing the reference to `opts`:

```javascript
gulp.task('css', gulp.series(function() {
  return gulp.src(src.css)
    .pipe(minifyCSS())
```

This is the same thing as what it was doing before, because previously the undefined variable would have just defaulted to the value `undefined` which is the same as not providing the argument at all.

2022-10-07 08:12 UTC, Divs-B commented on build/gulpfile.js
> +    //.pipe(gulp.dest(out.css))
good spot, i should have verified these changes that were done in previous modification. will do and test.

2022-10-07 08:13 UTC, Divs-B commented on build/gulpfile.js
> +    //.pipe(minifyCSS(opts))
Agreed! it is working with de-referencing the opts due to current gulp version. will check in the changes. thankyou.

2022-10-07 08:14 UTC, Divs-B commented on README.md
>  gulp
Sure, will do the required changes.

2022-10-07 13:13 UTC, fredex42 approved these changes
One little change then good to merge!

2022-10-07 13:13 UTC, fredex42 commented on build/gulpfile.js
>      //.pipe(concat('all.min.css'))
we usually remove commented-out lines before merging.  Have you checked that the CSS still renders ok with this file famoved?

2022-10-07 13:13 UTC, fredex42 commented on README.md
>  gulp
👍

2022-10-07 13:13 UTC, fredex42 commented on build/gulpfile.js
> +    //.pipe(gulp.dest(out.css))
👍

2022-10-07 13:13 UTC, fredex42 commented on build/gulpfile.js
> +    //.pipe(minifyCSS(opts))
👍

2022-10-07 13:22 UTC, fredex42 commented
👍 Paul is away today but this is now clear to merge 😄

2022-10-07 13:22 UTC, Divs-B commented on build/gulpfile.js
>      //.pipe(concat('all.min.css'))
Yes I have tested against live site of documentation

2022-10-07 14:04 UTC, Divs-B commented on build/gulpfile.js
>      //.pipe(concat('all.min.css'))
Thanks Andy for looking into the PR, as discussed I removed concat from gulpfile.js and from package.json then did npm install again and then check-in the file.  Tested one more time against the live platform site as well.

2022-10-07 14:05 UTC, merged